### ISSUE TITLE
Fix enum mapping for hole details

### ISSUE THREAD

**Issue by mrkdir** [jonasnikolaus/NXOpen_FAU#1]
`print_hole_details()` prints "Unknown Type" for hole type and form because those are Enum instances:
https://github.com/jonasnikolaus/NXOpen_FAU/blob/6180f157a2868ac8340c9bdcf60bc9a515d49a06/kombinationen/dividedcode.py#L136-L138

Instead the value of the Enums should used to map the description like:
```
 hole_type = hole_builder.Type.value
 boolean_operation = hole_builder.BooleanOperation
 general_hole_form = hole_builder.GeneralHoleForm.value
```

**Comment by jonasnikolaus** [comment]
Issue resolved
